### ISSUE TITLE
Finally and Observer.Using should be serialized with OnNext and OnComplete/OnError on unsubscribe.

### ISSUE THREAD

**Issue by Dorus** [dotnet/reactive#112]
As per the design guidelines, all calls to OnNext and OnComplete are serialized. When a sequence terminate cleanly with a OnComplete or OnError, Finally and Observer.Using neatly execute serialized.

However, when [unsubscribing a subscription using Dispose()](http://stackoverflow.com/questions/29847430/close-unmanaged-resources-when-subscription-end-in-reactive-extensions), the unsubscription happens on the thread calling Dispose(), and runs parallel with ongoing calls to OnNext.

**Comment by Dorus** [comment]
Ps. I had this in my backlog for 2 months now. Could be #106 has already fixed this.

**Comment by shiftkey** [comment]
@Dorus could you confirm this is resolved in `3.0.0` - I'm not sure on the best way to reproduce this issue...

**Comment by Dorus** [comment]
The following console app prints "Oops" for me. 
```C#
static void Main(string[] args)
{
    var running = false;
    var sub = Observable.Return(0)
        .ObserveOn(Scheduler.Default)
        .Finally(() =>
        {
            if (running)
            {
                Console.WriteLine("Oops!");
            }
            else
            {
                Console.WriteLine("Yay!");
            }
        }).Subscribe(e =>
        {
            running = true;
            Thread.Sleep(100);
            running = false;
        });
    Thread.Sleep(50);
    sub.Dispose();
    Console.ReadLine();
}
```

As does the following snipped:

```C#
static void Main(string[] args)
{
    var running = false;
    var obs = Observable.Return(0)
        .ObserveOn(Scheduler.Default);
    var source = Observable.Using(() => Disposable.Create(() =>
    {
        if (running)
        {
            Console.WriteLine("Oops!");
        }
        else
        {
            Console.WriteLine("Yay!");
        }
    }), _ => obs);
    var sub = source.Subscribe(e =>
        {
            running = true;
            Thread.Sleep(100);
            running = false;
        });
    Thread.Sleep(50);
    sub.Dispose();
    Console.ReadLine();
}
```
Both tested in 3.0.0 and latest.

I was unable to reproduce this using the `testScheduler`, as the problem seems to come from concurrently calling `Dispose` and `onNext`. Something the `testScheduler` wont do.

**Comment by andrekoehler** [comment]
I just tested, this issue still exists using the test code posted by @Dorus above in Rx v3.1.1 from nuget. I do really not understand why something important like Dispose and Finally is not getting fixed.

**Comment by akarnokd** [comment]
This is a tough decision. If `Dispose` is serialized with `OnNext`, which could be blocking on a resource, disposing the sequence would never unblock that resource and the sequence remains hung.

**Comment by andrekoehler** [comment]
How about if the developer can pass a boolean somewhere during the creation of the sequence with which he can select if dispose is serialized or parallel.

**Comment by danielcweber** [comment]
@andrekoehler I can't see this happening. If every operator would have an IScheduler on where to put OnNext etc. you could maybe serialize it that way, but since that's not the case you would have to introduce blocking, and an additional parameter adds just another layer of complexity. Dispose (as any other notion of cancellation) can do only best-effort in some cases.

**Comment by akarnokd** [comment]
Closing as unlikely to happen.
